// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

function add2(x, y) {
  return x + y | 0;
}

var name = "Joe";

var greeting = "Hello\r\nWorld\r\n?\r\n" + name;

var message = "Today I am " + 10 + " years old.";

var r = /b/g;

var $$break = {
  contents: false
};

while(!$$break.contents) {
  if (Math.random() > 0.3) {
    $$break.contents = true;
  } else {
    console.log("Still running");
  }
};

var score = 10;

var myInt = 5;

var myInt1 = 5;

var myInt2 = 9;

var x = 10;

var a = [
  10,
  20,
  20
];

var b = [
  10.5,
  20.5,
  20.5
];

var multilineGreeting = "Hello\r\n world!";

var greetings = "Hello world!";

var age = 10;

var firstLetterOfAlphabet = /* 'a' */97;

var me = {
  TAG: /* Id */1,
  name: "Joe",
  password: "123"
};

exports.score = score;
exports.add = add;
exports.myInt = myInt;
exports.myInt1 = myInt1;
exports.myInt2 = myInt2;
exports.add2 = add2;
exports.x = x;
exports.a = a;
exports.b = b;
exports.multilineGreeting = multilineGreeting;
exports.greetings = greetings;
exports.name = name;
exports.greeting = greeting;
exports.age = age;
exports.message = message;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.r = r;
exports.me = me;
exports.$$break = $$break;
/*  Not a pure module */
